import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import tailwindcss from '@tailwindcss/vite';

// Nemesis Vite Config — generated by `php nemesis vite:init`
// Docs: https://vitejs.dev/config/

export default defineConfig({
    plugins: [svelte(), tailwindcss()],
    build: {
        outDir: 'public/build',
        emptyOutDir: true,
        manifest: true,
        rollupOptions: {
            input: [
                'resources/js/svelte/app.js',
                'resources/css/app.css',
            ],
        },
    },
    server: {
        // HMR host — must match VITE_DEV_URL in .env
        host: 'localhost',
        port: 5173,
        // Write the hot file so AssetManager switches to HMR URLs
        hmr: {
            host: 'localhost',
        },
    },
    // Tell Vite where the public directory is
    publicDir: false,
});
